export const resourceIds = {
  contentTable: "ContentTable",
  contentBucket: "ContentBucket",
  siteBucket: "SiteBucket",
  readFunction: "ReadFunction",
  startRunFunction: "StartRunFunction",
  researchFunction: "ResearchFunction",
  publishFunction: "PublishFunction",
  recordFailureFunction: "RecordFailureFunction",
  workflow: "GenerationWorkflow",
  workflowLogGroup: "GenerationWorkflowLogGroup",
  schedulerDlq: "SchedulerDlq",
  scheduler: "DailyGenerationSchedule",
  publicApi: "PublicApi",
  webDistribution: "WebDistribution",
  schedulerFailureAlarm: "SchedulerFailureAlarm",
  schedulerDlqAlarm: "SchedulerDlqAlarm",
  workflowFailureAlarm: "WorkflowFailureAlarm",
} as const;
