import * as cdk from "aws-cdk-lib";
import { CfnOutput, Tags } from "aws-cdk-lib";
import { Construct } from "constructs";
import {
  challengeAppConfig,
  type CreativeAgentConfig,
} from "../config/app-config";
import { ContentStore } from "../constructs/content-store";
import { GenerationWorkflow } from "../constructs/generation-workflow";
import { PublicApi } from "../constructs/public-api";
import { WebDelivery } from "../constructs/web-delivery";

export { challengeAppConfig } from "../config/app-config";

export interface CreativeAgentStackProps extends cdk.StackProps {
  readonly config: CreativeAgentConfig;
}

export class CreativeAgentStack extends cdk.Stack {
  public constructor(
    scope: Construct,
    id: string,
    props: CreativeAgentStackProps,
  ) {
    super(scope, id, props);
    Tags.of(this).add("Environment", props.config.environment);
    Tags.of(this).add("Project", "weekend-creative-agent");

    const store = new ContentStore(this, "ContentStore");
    const workflow = new GenerationWorkflow(this, "Generation", {
      config: props.config,
      store,
    });
    const api = new PublicApi(this, "PublicReadApi", {
      config: props.config,
      store,
    });
    const web = new WebDelivery(this, "WebDelivery", { api, store });

    new CfnOutput(this, "PublicUrl", {
      description: "CloudFront URL for the public read-only application.",
      value: `https://${web.distribution.distributionDomainName}`,
    });
    new CfnOutput(this, "StateMachineArn", {
      description: "Generation state machine ARN.",
      value: workflow.stateMachine.stateMachineArn,
    });

    this.node.addMetadata(cdk.Validations.ACKNOWLEDGED_RULES_METADATA_KEY, {
      "AwsSolutions-S1":
        "CloudFront and CloudWatch provide access telemetry; a third logging bucket is outside the challenge scope.",
      "AwsSolutions-IAM4[Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole]":
        "The AWS managed basic execution policy is limited to Lambda log delivery.",
      "AwsSolutions-IAM5[Resource::<ContentStoreContentTable2F26E2EB.Arn>/index/*]":
        "DynamoDB index ARNs are generated by CDK and required for the two named GSIs.",
      "AwsSolutions-IAM5[Action::s3:Abort*]":
        "Bucket grants generated by CDK require the bounded S3 multipart-abort action family.",
      "AwsSolutions-IAM5[Action::s3:DeleteObject*]":
        "Challenge cleanup uses generated object-delete permissions only on owned buckets.",
      "AwsSolutions-IAM5[Action::s3:GetBucket*]":
        "CDK bucket grants require bounded bucket metadata actions.",
      "AwsSolutions-IAM5[Action::s3:GetObject*]":
        "CDK bucket grants require object-version compatible reads on the owned content bucket.",
      "AwsSolutions-IAM5[Action::s3:List*]":
        "CDK bucket grants require list actions scoped to the owned bucket.",
      "AwsSolutions-IAM5[Resource::<ContentStoreContentBucket805AA8FE.Arn>/*]":
        "Content object access is limited to this stack-owned bucket.",
      "AwsSolutions-IAM5[Resource::<GenerationPublishFunctionAA5E28CA.Arn>:*]":
        "Step Functions invokes only this stack-owned Lambda and its qualified versions.",
      "AwsSolutions-IAM5[Resource::<GenerationRecordFailureFunction1A4B7E5C.Arn>:*]":
        "Step Functions invokes only this stack-owned Lambda and its qualified versions.",
      "AwsSolutions-IAM5[Resource::<GenerationResearchFunction11F59290.Arn>:*]":
        "Step Functions invokes only this stack-owned Lambda and its qualified versions.",
      "AwsSolutions-IAM5[Resource::<GenerationStartRunFunctionD7D04E6F.Arn>:*]":
        "Step Functions invokes only this stack-owned Lambda and its qualified versions.",
      "AwsSolutions-IAM5[Resource::*]":
        "The CDK deployment custom resource needs its generated asset location; no application role receives this permission.",
      "AwsSolutions-IAM5[Resource::arn:aws:s3:::cdk-hnb659fds-assets-<AWS::AccountId>-ap-northeast-1/*]":
        "The CDK deployment custom resource can read only the bootstrap asset bucket.",
      "AwsSolutions-IAM5[Resource::arn:aws:s3:::cdk-hnb659fds-assets-796032104877-ap-northeast-1/*]":
        "The CDK deployment custom resource can read only this account's bootstrap asset bucket.",
      "AwsSolutions-IAM5[Resource::<ContentStoreSiteBucket5592CE0B.Arn>/*]":
        "The deployment custom resource writes only the stack-owned site bucket.",
      "AwsSolutions-SQS3":
        "This queue is the terminal Scheduler delivery DLQ and is not a processing queue.",
      "AwsSolutions-SQS4":
        "Scheduler-to-DLQ delivery is an AWS service integration; the queue policy restricts its service principal and source ARN.",
      "AwsSolutions-APIG4":
        "The API deliberately exposes published content as unauthenticated read-only GET routes.",
      "AwsSolutions-APIG1":
        "The public API returns no secrets; Lambda structured logs and workflow logs provide operational tracing in the challenge scope.",
      "AwsSolutions-CFR3":
        "CloudFront request logging is outside the minimal challenge scope; application and workflow logs are retained in CloudWatch.",
      "AwsSolutions-CFR4":
        "The default CloudFront certificate is retained for the challenge URL; a custom domain and certificate are out of scope.",
      "AwsSolutions-CFR1":
        "The public Community Builder application is intentionally available globally.",
      "AwsSolutions-CFR2":
        "WAF is deferred for the low-volume, read-only challenge environment; throttling and reserved concurrency limit API load.",
      "AwsSolutions-L1":
        "The CDK BucketDeployment provider runtime is controlled by CDK; application Lambdas use Node.js 24.",
    });
  }
}
